Sleepy:
  Hollow: "안녕하세요"
  test: "처음 하는 yml"
  onlydefault: "defaulty profile only"

---

spring:
  profiles: stage
Sleepy:
  Hollow: "안녕하세요"
  test: "처음 하는 yml - stage server."
  onlyeachprofile: "only - stage"


---

spring:
  profiles: dev
Sleepy:
  Hollow: "안녕하세요"
  test: "처음 하는 yml - dev server."
  onlyeachprofile: "only - dev"


---

spring:
  profiles: local
Sleepy:
  Hollow: "안녕하세요"
  test: "처음 하는 yml - local server."
  onlydefault: "override default"
